[[redirects]]
  from = "https://magnoliajs.com"
  to = "https://2025.magnoliaconf.com"

[[redirects]]
  from = "https://magnoliaconf.com"
  to = "https://2025.magnoliaconf.com"


[[redirects]]
  from = "https://www.magnoliaconf.com"
  to = "https://2025.magnoliaconf.com"

[[redirects]]
  from = "https://www.magnoliajs.com"
  to = "https://2025.magnoliaconf.com"

[[redirects]]
  from = "https://magnoliajs.boo"
  to = "https://2025.magnoliaconf.com"